#!/usr/bin/expect -f

cd ~/rl-swarm
spawn docker-compose run -Pit swarm-cpu

expect {
    -re ">> Please open http://localhost:3000.*" {
        exec open -a "Firefox" http://localhost:3000
        sleep 30
        exec osascript -e {tell application "Firefox" to quit}
    }
}

expect {
    -re "Would you like to push models.*" { send "n\r" }
}
expect {
    -re "Enter the name.*" { send "\r" }
}
expect {
    -re "AI Prediction Market.*" { send "n\r" }
}

interact
